-- =========================================================================
--  Sunrise Dental Clinic Management System
--  V1 : baseline schema (H2 profile)
--  CIS6003 Advanced Programming - WRIT1, Task B (iii) "proper database"
-- =========================================================================
--  The schema is owned by Flyway, not by Hibernate. Hibernate runs with
--  ddl-auto=validate, so it verifies that the Java model still matches these
--  tables and refuses to start if it does not. That inverts the usual student
--  arrangement (auto-generated tables) and gives a schema that can be code
--  reviewed, versioned in Git and applied to a production database safely.
-- =========================================================================


-- -------------------------------------------------------------------------
-- Staff accounts. Requirement 1: "User Authentication (Login)".
-- Named app_user because USER is a reserved word in H2 and MySQL.
-- -------------------------------------------------------------------------
CREATE TABLE app_user (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(30)  NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    full_name             VARCHAR(100) NOT NULL,
    email                 VARCHAR(120),
    role                  VARCHAR(20)  NOT NULL,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at         TIMESTAMP,
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP,
    linked_dentist_code   VARCHAR(20),
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP,
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_app_user_username UNIQUE (username),
    CONSTRAINT chk_app_user_role CHECK (role IN ('ADMIN', 'RECEPTIONIST', 'DENTIST'))
);


-- -------------------------------------------------------------------------
-- Patient master file. A patient exists ONCE; every visit points at it.
-- This is the fix for "lost patient records" in the scenario.
-- -------------------------------------------------------------------------
CREATE TABLE patient (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code   VARCHAR(20)  NOT NULL,
    full_name      VARCHAR(100) NOT NULL,
    address        VARCHAR(200) NOT NULL,
    contact_number VARCHAR(20)  NOT NULL,
    email          VARCHAR(120),
    nic            VARCHAR(20),
    gender         VARCHAR(20),
    date_of_birth  DATE,
    medical_notes  VARCHAR(500),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP,
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_patient_code UNIQUE (patient_code)
);

CREATE INDEX ix_patient_name    ON patient (full_name);
CREATE INDEX ix_patient_contact ON patient (contact_number);


-- -------------------------------------------------------------------------
-- Dentists. Consultation fee and shift hours live per dentist, because the
-- bill is "based on treatment type AND consultation fee" and a senior
-- orthodontist does not charge a junior's rate.
-- -------------------------------------------------------------------------
CREATE TABLE dentist (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dentist_code         VARCHAR(20)   NOT NULL,
    full_name            VARCHAR(100)  NOT NULL,
    specialization       VARCHAR(80)   NOT NULL,
    contact_number       VARCHAR(20)   NOT NULL,
    email                VARCHAR(120),
    consultation_fee     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    slmc_registration_no VARCHAR(40),
    work_start_time      TIME          NOT NULL DEFAULT '08:00:00',
    work_end_time        TIME          NOT NULL DEFAULT '20:00:00',
    active               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    version              BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_dentist_code UNIQUE (dentist_code),
    CONSTRAINT chk_dentist_fee   CHECK (consultation_fee >= 0),
    CONSTRAINT chk_dentist_shift CHECK (work_end_time > work_start_time)
);


-- -------------------------------------------------------------------------
-- Treatment catalogue = the scenario's "treatment type".
-- A table rather than a Java enum, so prices and new treatments are data.
-- pricing_strategy is the key the Strategy factory resolves at run time.
-- -------------------------------------------------------------------------
CREATE TABLE treatment (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(20)   NOT NULL,
    name             VARCHAR(100)  NOT NULL,
    description      VARCHAR(300),
    category         VARCHAR(50)   NOT NULL,
    base_price       DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    duration_minutes INTEGER       NOT NULL DEFAULT 30,
    pricing_strategy VARCHAR(30)   NOT NULL DEFAULT 'STANDARD',
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP     NOT NULL,
    updated_at       TIMESTAMP,
    version          BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_treatment_code  UNIQUE (code),
    CONSTRAINT chk_treatment_price CHECK (base_price >= 0),
    CONSTRAINT chk_treatment_duration CHECK (duration_minutes BETWEEN 15 AND 480)
);


-- -------------------------------------------------------------------------
-- Appointments. Requirement 2: "Register New Appointment".
--
--  *** THE ANTI-DOUBLE-BOOKING RULE ***
--  slot_lock holds 'yyyy-MM-dd|HH:mm' while the appointment occupies the
--  dentist's chair and NULL once it is cancelled or marked a no-show.
--  uk_appointment_slot (dentist_id, slot_lock) therefore refuses a second
--  LIVE booking for the same dentist and time, while permitting any number of
--  cancelled ones - because a unique index never compares two NULLs as equal.
--  The rule is enforced by the database, so no application bug, concurrent
--  request or direct SQL edit can reintroduce the clinic's original problem.
-- -------------------------------------------------------------------------
CREATE TABLE appointment (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_number  VARCHAR(20)  NOT NULL,
    patient_id          BIGINT       NOT NULL,
    dentist_id          BIGINT       NOT NULL,
    treatment_id        BIGINT       NOT NULL,
    appointment_date    DATE         NOT NULL,
    appointment_time    TIME         NOT NULL,
    duration_minutes    INTEGER      NOT NULL DEFAULT 30,
    status              VARCHAR(20)  NOT NULL DEFAULT 'SCHEDULED',
    slot_lock           VARCHAR(30),
    notes               VARCHAR(500),
    cancellation_reason VARCHAR(300),
    created_by          VARCHAR(30)  NOT NULL,
    updated_by          VARCHAR(30),
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP,
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_appointment_number UNIQUE (appointment_number),
    CONSTRAINT uk_appointment_slot   UNIQUE (dentist_id, slot_lock),
    CONSTRAINT fk_appointment_patient   FOREIGN KEY (patient_id)   REFERENCES patient (id),
    CONSTRAINT fk_appointment_dentist   FOREIGN KEY (dentist_id)   REFERENCES dentist (id),
    CONSTRAINT fk_appointment_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (id),
    CONSTRAINT chk_appointment_status CHECK
        (status IN ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT chk_appointment_duration CHECK (duration_minutes > 0)
);

CREATE INDEX ix_appointment_date    ON appointment (appointment_date);
CREATE INDEX ix_appointment_patient ON appointment (patient_id);
CREATE INDEX ix_appointment_status  ON appointment (status);
CREATE INDEX ix_appointment_dentist_date ON appointment (dentist_id, appointment_date);


-- -------------------------------------------------------------------------
-- Invoices. Requirement 4: "Calculate and Print Bill".
-- Every figure is stored, and the patient details are copied, because a bill
-- is a historic legal record that must not change when the price list does.
-- uk_invoice_appointment makes "billed twice" structurally impossible.
-- -------------------------------------------------------------------------
CREATE TABLE invoice (
    id                       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number           VARCHAR(20)   NOT NULL,
    appointment_id           BIGINT        NOT NULL,
    patient_name             VARCHAR(100)  NOT NULL,
    patient_address          VARCHAR(200)  NOT NULL,
    patient_contact          VARCHAR(20)   NOT NULL,
    dentist_name             VARCHAR(100)  NOT NULL,
    treatment_name           VARCHAR(100)  NOT NULL,
    consultation_fee         DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    treatment_cost           DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    surcharge_amount         DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    sub_total                DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_percentage      DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
    discount_amount          DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_reason          VARCHAR(200),
    taxable_amount           DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    tax_rate                 DECIMAL(5,4)  NOT NULL DEFAULT 0.1800,
    tax_amount               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_amount             DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    amount_paid              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    pricing_strategy_applied VARCHAR(30),
    payment_status           VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    payment_method           VARCHAR(20),
    payment_reference        VARCHAR(100),
    issued_date              DATE          NOT NULL,
    issued_by                VARCHAR(30)   NOT NULL,
    paid_at                  TIMESTAMP,
    remarks                  VARCHAR(300),
    created_at               TIMESTAMP     NOT NULL,
    updated_at               TIMESTAMP,
    version                  BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT uk_invoice_number      UNIQUE (invoice_number),
    CONSTRAINT uk_invoice_appointment UNIQUE (appointment_id),
    CONSTRAINT fk_invoice_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (id),
    CONSTRAINT chk_invoice_payment_status CHECK
        (payment_status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')),
    CONSTRAINT chk_invoice_discount_pct CHECK (discount_percentage BETWEEN 0 AND 50),
    CONSTRAINT chk_invoice_amounts      CHECK (total_amount >= 0 AND amount_paid >= 0),
    -- a bill can never be over-paid; enforced by the database, not by trust
    CONSTRAINT chk_invoice_amount_paid  CHECK (amount_paid <= total_amount)
);

CREATE INDEX ix_invoice_issued_date    ON invoice (issued_date);
CREATE INDEX ix_invoice_payment_status ON invoice (payment_status);


-- -------------------------------------------------------------------------
-- Printed breakdown of a bill: consultation, treatment, surcharge, discount
-- and VAT each appear as their own line, so a patient can see WHY the total
-- is what it is. Directly targets the "billing errors" complaint.
-- -------------------------------------------------------------------------
CREATE TABLE invoice_line (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT        NOT NULL,
    line_number INTEGER       NOT NULL,
    description VARCHAR(200)  NOT NULL,
    quantity    INTEGER       NOT NULL DEFAULT 1,
    unit_price  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_total  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_type   VARCHAR(20)   NOT NULL DEFAULT 'CHARGE',
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP,
    version     BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT fk_invoice_line_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE,
    CONSTRAINT chk_invoice_line_type CHECK (line_type IN ('CHARGE', 'SURCHARGE', 'DISCOUNT', 'TAX')),
    CONSTRAINT chk_invoice_line_qty  CHECK (quantity > 0)
);

CREATE INDEX ix_invoice_line_invoice ON invoice_line (invoice_id);


-- -------------------------------------------------------------------------
-- Append-only audit trail. Rows arrive from the application AND from the
-- database triggers declared in V4, so changes made outside this application
-- are still recorded. source distinguishes the two.
-- -------------------------------------------------------------------------
CREATE TABLE audit_log (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)   NOT NULL,
    action      VARCHAR(60)   NOT NULL,
    entity_type VARCHAR(50),
    entity_key  VARCHAR(50),
    details     VARCHAR(1000),
    ip_address  VARCHAR(60),
    source      VARCHAR(20)   NOT NULL DEFAULT 'APPLICATION',
    occurred_at TIMESTAMP     NOT NULL
);

CREATE INDEX ix_audit_log_occurred ON audit_log (occurred_at);
CREATE INDEX ix_audit_log_username ON audit_log (username);
CREATE INDEX ix_audit_log_entity   ON audit_log (entity_type, entity_key);


-- -------------------------------------------------------------------------
-- Proof of every appointment alert attempted, successful or not.
-- -------------------------------------------------------------------------
CREATE TABLE notification_log (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel        VARCHAR(20)   NOT NULL,
    recipient      VARCHAR(150)  NOT NULL,
    subject        VARCHAR(200),
    body           VARCHAR(2000),
    status         VARCHAR(20)   NOT NULL DEFAULT 'SENT',
    failure_reason VARCHAR(500),
    reference_key  VARCHAR(30),
    created_at     TIMESTAMP     NOT NULL,
    CONSTRAINT chk_notification_channel CHECK (channel IN ('EMAIL', 'SMS', 'SYSTEM')),
    CONSTRAINT chk_notification_status  CHECK (status IN ('SENT', 'FAILED', 'SUPPRESSED'))
);

CREATE INDEX ix_notification_log_sent      ON notification_log (created_at);
CREATE INDEX ix_notification_log_reference ON notification_log (reference_key);


-- -------------------------------------------------------------------------
-- Counters behind APT-2026-000137 / INV-2026-000137 / PAT-000042.
-- One row per key, allocated under SELECT ... FOR UPDATE, so two receptionists
-- saving in the same second cannot be issued the same number.
-- -------------------------------------------------------------------------
CREATE TABLE number_sequence (
    sequence_key VARCHAR(40) NOT NULL PRIMARY KEY,
    next_value   BIGINT      NOT NULL DEFAULT 1,
    CONSTRAINT chk_number_sequence_value CHECK (next_value > 0)
);
